In [1]:
# import important libaries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder , OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LinearRegression

In [24]:
# read data from local disk
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\archive (41).zip")
df

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,660.30,10,3.8,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,470.50,8,3.0,False,27,Neutral
347,448,Female,30,New York,Gold,1190.80,16,4.5,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,780.20,11,4.2,False,21,Neutral
349,450,Female,43,Chicago,Bronze,515.75,10,3.3,True,49,Unsatisfied

In [35]:
# rename the column name 
df["Discount_Applied"] = df ["Discount Applied"]

In [46]:
df = df[['Gender', 'Age', 'City', 'Membership Type',
       'Total Spend', 'Items Purchased', 'Average Rating', 'Discount_Applied',
       'Days Since Last Purchase', 'Satisfaction Level']]

In [47]:
# Classify data into Numerical or Categorical
cat = X.select_dtypes(include= ["object"]).columns
num = X.select_dtypes(exclude= ["object"]).columns

In [49]:
# Split target and feature columns
X = df.drop(columns=['Discount_Applied'], axis=1)
y = df['Discount_Applied']

In [50]:

from sklearn.compose import ColumnTransformer
pre = ColumnTransformer(
    transformers=[
        ("cat",OneHotEncoder(), cat),
        ("num", StandardScaler(),num)
    ]
)
pre

ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                 Index(['Gender', 'City', 'Membership Type', 'Satisfaction Level'], dtype='object')),
                                ('num', StandardScaler(),
                                 Index(['Age', 'Total Spend', 'Items Purchased', 'Average Rating',
       'Days Since Last Purchase'],
      dtype='object'))])

In [52]:
# make pipeline for model and make a model
from sklearn.pipeline import Pipeline

model= Pipeline(steps=[
    ("Preprocesser", pre),
    ("Logistic", LogisticRegression())
])
model

Pipeline(steps=[('Preprocesser',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Gender', 'City', 'Membership Type', 'Satisfaction Level'], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['Age', 'Total Spend', 'Items Purchased', 'Average Rating',
       'Days Since Last Purchase'],
      dtype='object'))])),
                ('Logistic', LogisticRegression())])

In [53]:
# Split into Training and Testing
X_train,X_test, y_train , y_test= train_test_split(X,y, test_size=.2, random_state=40)

In [54]:
# Fiting a  model into train data 
model.fit(X_train, y_train)

Pipeline(steps=[('Preprocesser',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['Gender', 'City', 'Membership Type', 'Satisfaction Level'], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['Age', 'Total Spend', 'Items Purchased', 'Average Rating',
       'Days Since Last Purchase'],
      dtype='object'))])),
                ('Logistic', LogisticRegression())])

In [55]:
y_pred = model.predict(X_test)

In [56]:
# check accuarcy of model
from sklearn.metrics import accuracy_score , confusion_matrix
acc = accuracy_score(y_pred , y_test)
con  = confusion_matrix(y_pred , y_test)

print("Model accuarcy :",acc)
print("Confusion metrics :",con)

Model accuarcy : 1.0
Confusion metrics : [[36  0]
 [ 0 34]]

In [57]:
df.head()

,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount_Applied,Days Since Last Purchase,Satisfaction Level
0,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied

In [ ]:
# take live input for model test
live = pd.DataFrame({
    'Gender' :["Male"], 
    'Age' : [30], 
    'City' : ["San Francisco"], 
    'Membership Type' : ["Gold"], 
    'Total Spend' : [1480.20],
    'Items Purchased' : [19], 
    'Average Rating' : [4.7],
    'Days Since Last Purchase' : [12], 
    'Satisfaction Level' : ["Satisfied"]
})

In [69]:
# Use [0][1] to get the probability of the positive class for the first sample
prob = model.predict_proba(live)
positive_prob = prob[0][1] 

result = 'Discount_Applied' if positive_prob > 0.50 else "not"

print("prediction :", result)
print("positive Probability :", positive_prob)

prediction : not
positive Probability : 0.027376946131169956